# Makefile definitions particular to the MOOSNav library

LTARGET  = libMOOSNav.a
LIFLAGS  = -I../newmat10a/
LCFLAGS  = -DUNIX

# Make configuration parameters
include ../make_config.mk
# Generic makefile structure for all library modules
include ../make_lib.mk
# DO NOT DELETE
