#------------------------------------------------------------
# Makefile for libbehaviors-attic.a
# Makefile by Mike Benjamin

LTARGET  = libbehaviors-attic.a
LIFLAGS  = 
LCFLAGS  = 

all:
	@echo "skipping library " $(LTARGET)

depend:

clean:
	@echo Finished cleaning $(LTARGET)


# Make configuration parameters
#include ../make_config.mk
# Generic makefile structure for all library modules
#include ../make_lib.mk
# DO NOT DELETE
