# Makefile definitions particular to the abahr_util library

LTARGET  = libabahr_util.a
LIFLAGS  = -I../gsl-1.9
LCFLAGS  = 

REQUIRED_MOOS_LIBS = 			\
	libMOOS.a 			\
	libMOOSUtility.a 		\
	libMOOSGen.a 		

# Make configuration parameters
include ../../make_config.mk
# Generic makefile structure for all library modules
include ../../make_lib.mk
# DO NOT DELETE
