# Makefile definitions particular to behaviors-nicop library

LTARGET  = libbehaviors-nicop.a
LIFLAGS  = -I../newmat10a
LCFLAGS  = 

# Make configuration parameters
include ../make_config.mk
# Generic makefile structure for all library modules
include ../make_lib.mk
# DO NOT DELETE
