# Makefile definitions particular to the behaviors library

LTARGET  = libbehaviors.a
LIFLAGS  = 
LCFLAGS  = 

# Make configuration parameters
include ../make_config.mk
# Generic makefile structure for all library modules
include ../make_lib.mk
# DO NOT DELETE

BehaviorSet.o: BehaviorSet.h IvPBehavior.h ../lib_ivpcore/IvPFunction.h
BehaviorSet.o: ../lib_ivpcore/IvPBox.h ../lib_ivpcore/PDMap.h
BehaviorSet.o: ../lib_ivpcore/BoxSet.h ../lib_ivpcore/BoxSetNode.h
BehaviorSet.o: ../lib_ivpcore/IvPGrid.h ../lib_ivpcore/IvPDomain.h
BehaviorSet.o: InfoBuffer.h VarDataPair.h ../lib_logic/LogicCondition.h
BehaviorSet.o: ../lib_logic/ParseNode.h ../lib_mbutil/MBUtils.h
BehaviorSet.o: /usr/include/time.h /usr/include/features.h
BehaviorSet.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
BehaviorSet.o: /usr/include/bits/time.h /usr/include/bits/types.h
BehaviorSet.o: /usr/include/bits/wordsize.h /usr/include/bits/typesizes.h
BehaviorSet.o: ../lib_ivpbuild/FunctionEncoder.h
InfoBuffer.o: InfoBuffer.h
IvPBehavior.o: IvPBehavior.h ../lib_ivpcore/IvPFunction.h
IvPBehavior.o: ../lib_ivpcore/IvPBox.h ../lib_ivpcore/PDMap.h
IvPBehavior.o: ../lib_ivpcore/BoxSet.h ../lib_ivpcore/BoxSetNode.h
IvPBehavior.o: ../lib_ivpcore/IvPGrid.h ../lib_ivpcore/IvPDomain.h
IvPBehavior.o: InfoBuffer.h VarDataPair.h ../lib_logic/LogicCondition.h
IvPBehavior.o: ../lib_logic/ParseNode.h ../lib_mbutil/MBUtils.h
IvPBehavior.o: /usr/include/time.h /usr/include/features.h
IvPBehavior.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
IvPBehavior.o: /usr/include/bits/time.h /usr/include/bits/types.h
IvPBehavior.o: /usr/include/bits/wordsize.h /usr/include/bits/typesizes.h
IvPBehavior.o: ../lib_ivpbuild/BuildUtils.h
VarDataPair.o: VarDataPair.h ../lib_mbutil/MBUtils.h /usr/include/time.h
VarDataPair.o: /usr/include/features.h /usr/include/sys/cdefs.h
VarDataPair.o: /usr/include/gnu/stubs.h /usr/include/bits/time.h
VarDataPair.o: /usr/include/bits/types.h /usr/include/bits/wordsize.h
VarDataPair.o: /usr/include/bits/typesizes.h
