# Makefile definitions particular to MOOSLIB library

LTARGET  = libMOOS.a
LIFLAGS  = -I../MOOSGenLib
LCFLAGS  = -DUNIX

# Make configuration parameters
include ../make_config.mk
# Generic makefile structure for all library modules
include ../make_lib.mk
# DO NOT DELETE
