# Makefile definitions particular to the MOOSGen library

LTARGET  = libMOOSGen.a
LIFLAGS  = 
LCFLAGS  = -DUNIX

# Make configuration parameters
include ../make_config.mk
# Generic makefile structure for all library modules
include ../make_lib.mk
# DO NOT DELETE
