# Makefile definitions particular to behaviors-sandbox library

LTARGET  = libbehaviors-sandbox.a
LIFLAGS  = 
LCFLAGS  = 

# Make configuration parameters
include ../make_config.mk
# Generic makefile structure for all library modules
include ../make_lib.mk
# DO NOT DELETE

AOF_AvoidCollisionTOL.o: /usr/include/math.h /usr/include/features.h
AOF_AvoidCollisionTOL.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
AOF_AvoidCollisionTOL.o: /usr/include/bits/huge_val.h
AOF_AvoidCollisionTOL.o: /usr/include/bits/mathdef.h
AOF_AvoidCollisionTOL.o: /usr/include/bits/mathcalls.h
AOF_AvoidCollisionTOL.o: AOF_AvoidCollisionTOL.h ../lib_ivpbuild/AOF.h
AOF_AvoidCollisionTOL.o: ../lib_ivpcore/IvPBox.h ../lib_ivpcore/IvPDomain.h
AOF_AvoidCollisionTOL.o: ../lib_geometry/CPAEngine.h
AOF_AvoidCollisionTOL.o: ../lib_geometry/AngleUtils.h
AOF_AvoidObstacles.o: /usr/include/math.h /usr/include/features.h
AOF_AvoidObstacles.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
AOF_AvoidObstacles.o: /usr/include/bits/huge_val.h
AOF_AvoidObstacles.o: /usr/include/bits/mathdef.h
AOF_AvoidObstacles.o: /usr/include/bits/mathcalls.h AOF_AvoidObstacles.h
AOF_AvoidObstacles.o: ../lib_ivpbuild/AOF.h ../lib_ivpcore/IvPBox.h
AOF_AvoidObstacles.o: ../lib_ivpcore/IvPDomain.h ../lib_geometry/XYPolygon.h
AOF_AvoidObstacles.o: ../lib_geometry/XYSegList.h
AOF_AvoidObstacles.o: ../lib_geometry/AngleUtils.h
AOF_AvoidObstacles.o: ../lib_geometry/GeomUtils.h
AOF_CutRangeFCPA.o: /usr/include/math.h /usr/include/features.h
AOF_CutRangeFCPA.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
AOF_CutRangeFCPA.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
AOF_CutRangeFCPA.o: /usr/include/bits/mathcalls.h AOF_CutRangeFCPA.h
AOF_CutRangeFCPA.o: ../lib_ivpbuild/AOF.h ../lib_ivpcore/IvPBox.h
AOF_CutRangeFCPA.o: ../lib_ivpcore/IvPDomain.h ../lib_geometry/CPAEngine.h
AOF_CutRangeFCPA.o: ../lib_geometry/AngleUtils.h
AOF_GENERIC.o: /usr/include/math.h /usr/include/features.h
AOF_GENERIC.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
AOF_GENERIC.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
AOF_GENERIC.o: /usr/include/bits/mathcalls.h /usr/include/assert.h
AOF_GENERIC.o: AOF_GENERIC.h ../lib_ivpbuild/AOF.h ../lib_ivpcore/IvPBox.h
AOF_GENERIC.o: ../lib_ivpcore/IvPDomain.h ../lib_geometry/AngleUtils.h
AOF_OpArea.o: /usr/include/math.h /usr/include/features.h
AOF_OpArea.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
AOF_OpArea.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
AOF_OpArea.o: /usr/include/bits/mathcalls.h /usr/include/assert.h
AOF_OpArea.o: AOF_OpArea.h ../lib_ivpbuild/AOF.h ../lib_ivpcore/IvPBox.h
AOF_OpArea.o: ../lib_ivpcore/IvPDomain.h ../lib_geometry/XYPolygon.h
AOF_OpArea.o: ../lib_geometry/XYSegList.h ../lib_geometry/AngleUtils.h
AOF_OpArea.o: ../lib_geometry/GeomUtils.h
AOF_SearchGrid.o: /usr/include/math.h /usr/include/features.h
AOF_SearchGrid.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
AOF_SearchGrid.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
AOF_SearchGrid.o: /usr/include/bits/mathcalls.h /usr/include/assert.h
AOF_SearchGrid.o: AOF_SearchGrid.h ../lib_ivpbuild/AOF.h
AOF_SearchGrid.o: ../lib_ivpcore/IvPBox.h ../lib_ivpcore/IvPDomain.h
AOF_SearchGrid.o: ../lib_geometry/XYGrid.h ../lib_geometry/XYSquare.h
AOF_SearchGrid.o: ../lib_geometry/XYPolygon.h ../lib_geometry/XYSegList.h
AOF_SearchGrid.o: Timutif.h ../lib_geometry/AngleUtils.h
AOF_SearchGrid.o: ../lib_mbutil/MBUtils.h /usr/include/time.h
AOF_SearchGrid.o: /usr/include/bits/time.h /usr/include/bits/types.h
AOF_SearchGrid.o: /usr/include/bits/wordsize.h /usr/include/bits/typesizes.h
AOF_TOL.o: AOF_TOL.h ../lib_ivpbuild/AOF.h ../lib_ivpcore/IvPBox.h
AOF_TOL.o: ../lib_ivpcore/IvPDomain.h
AOF_Waypoint2D.o: /usr/include/math.h /usr/include/features.h
AOF_Waypoint2D.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
AOF_Waypoint2D.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
AOF_Waypoint2D.o: /usr/include/bits/mathcalls.h /usr/include/assert.h
AOF_Waypoint2D.o: AOF_Waypoint2D.h ../lib_ivpbuild/AOF.h
AOF_Waypoint2D.o: ../lib_ivpcore/IvPBox.h ../lib_ivpcore/IvPDomain.h
AOF_Waypoint2D.o: ../lib_geometry/AngleUtils.h ../lib_mbutil/MBUtils.h
AOF_Waypoint2D.o: /usr/include/time.h /usr/include/bits/time.h
AOF_Waypoint2D.o: /usr/include/bits/types.h /usr/include/bits/wordsize.h
AOF_Waypoint2D.o: /usr/include/bits/typesizes.h
AOF_WaypointRateClosure.o: /usr/include/math.h /usr/include/features.h
AOF_WaypointRateClosure.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
AOF_WaypointRateClosure.o: /usr/include/bits/huge_val.h
AOF_WaypointRateClosure.o: /usr/include/bits/mathdef.h
AOF_WaypointRateClosure.o: /usr/include/bits/mathcalls.h
AOF_WaypointRateClosure.o: AOF_WaypointRateClosure.h ../lib_ivpbuild/AOF.h
AOF_WaypointRateClosure.o: ../lib_ivpcore/IvPBox.h ../lib_ivpcore/IvPDomain.h
AOF_WaypointRateClosure.o: ../lib_geometry/AngleUtils.h
AOF_WaypointRateClosure.o: ../lib_geometry/GeomUtils.h
BHV_AllStop.o: BHV_AllStop.h ../lib_behaviors/IvPBehavior.h
BHV_AllStop.o: ../lib_ivpcore/IvPFunction.h ../lib_ivpcore/IvPBox.h
BHV_AllStop.o: ../lib_ivpcore/PDMap.h ../lib_ivpcore/BoxSet.h
BHV_AllStop.o: ../lib_ivpcore/BoxSetNode.h ../lib_ivpcore/IvPGrid.h
BHV_AllStop.o: ../lib_ivpcore/IvPDomain.h ../lib_behaviors/InfoBuffer.h
BHV_AllStop.o: ../lib_behaviors/VarDataPair.h ../lib_logic/LogicCondition.h
BHV_AllStop.o: ../lib_logic/ParseNode.h ../lib_ivpbuild/ZAIC_PEAK.h
BHV_AllStop.o: ../lib_ivpbuild/OF_Coupler.h
BHV_AvoidCollisionTOL.o: /usr/include/math.h /usr/include/features.h
BHV_AvoidCollisionTOL.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
BHV_AvoidCollisionTOL.o: /usr/include/bits/huge_val.h
BHV_AvoidCollisionTOL.o: /usr/include/bits/mathdef.h
BHV_AvoidCollisionTOL.o: /usr/include/bits/mathcalls.h
BHV_AvoidCollisionTOL.o: ../lib_geometry/AngleUtils.h
BHV_AvoidCollisionTOL.o: ../lib_geometry/GeomUtils.h
BHV_AvoidCollisionTOL.o: ../lib_bhvutil/AOF_AvoidCollision.h
BHV_AvoidCollisionTOL.o: ../lib_ivpbuild/AOF.h ../lib_ivpcore/IvPBox.h
BHV_AvoidCollisionTOL.o: ../lib_ivpcore/IvPDomain.h
BHV_AvoidCollisionTOL.o: ../lib_geometry/CPAEngine.h BHV_AvoidCollisionTOL.h
BHV_AvoidCollisionTOL.o: ../lib_behaviors/IvPBehavior.h
BHV_AvoidCollisionTOL.o: ../lib_ivpcore/IvPFunction.h ../lib_ivpcore/PDMap.h
BHV_AvoidCollisionTOL.o: ../lib_ivpcore/BoxSet.h ../lib_ivpcore/BoxSetNode.h
BHV_AvoidCollisionTOL.o: ../lib_ivpcore/IvPGrid.h
BHV_AvoidCollisionTOL.o: ../lib_behaviors/InfoBuffer.h
BHV_AvoidCollisionTOL.o: ../lib_behaviors/VarDataPair.h
BHV_AvoidCollisionTOL.o: ../lib_logic/LogicCondition.h
BHV_AvoidCollisionTOL.o: ../lib_logic/ParseNode.h
BHV_AvoidCollisionTOL.o: ../lib_ivpbuild/OF_Reflector.h
BHV_AvoidCollisionTOL.o: ../lib_ivpbuild/BuildUtils.h ../lib_mbutil/MBUtils.h
BHV_AvoidCollisionTOL.o: /usr/include/time.h /usr/include/bits/time.h
BHV_AvoidCollisionTOL.o: /usr/include/bits/types.h
BHV_AvoidCollisionTOL.o: /usr/include/bits/wordsize.h
BHV_AvoidCollisionTOL.o: /usr/include/bits/typesizes.h
BHV_AvoidObstacles.o: /usr/include/math.h /usr/include/features.h
BHV_AvoidObstacles.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
BHV_AvoidObstacles.o: /usr/include/bits/huge_val.h
BHV_AvoidObstacles.o: /usr/include/bits/mathdef.h
BHV_AvoidObstacles.o: /usr/include/bits/mathcalls.h BHV_AvoidObstacles.h
BHV_AvoidObstacles.o: ../lib_behaviors/IvPBehavior.h
BHV_AvoidObstacles.o: ../lib_ivpcore/IvPFunction.h ../lib_ivpcore/IvPBox.h
BHV_AvoidObstacles.o: ../lib_ivpcore/PDMap.h ../lib_ivpcore/BoxSet.h
BHV_AvoidObstacles.o: ../lib_ivpcore/BoxSetNode.h ../lib_ivpcore/IvPGrid.h
BHV_AvoidObstacles.o: ../lib_ivpcore/IvPDomain.h
BHV_AvoidObstacles.o: ../lib_behaviors/InfoBuffer.h
BHV_AvoidObstacles.o: ../lib_behaviors/VarDataPair.h
BHV_AvoidObstacles.o: ../lib_logic/LogicCondition.h ../lib_logic/ParseNode.h
BHV_AvoidObstacles.o: AOF_AvoidObstacles.h ../lib_ivpbuild/AOF.h
BHV_AvoidObstacles.o: ../lib_geometry/XYPolygon.h ../lib_geometry/XYSegList.h
BHV_AvoidObstacles.o: ../lib_ivpbuild/OF_Reflector.h ../lib_mbutil/MBUtils.h
BHV_AvoidObstacles.o: /usr/include/time.h /usr/include/bits/time.h
BHV_AvoidObstacles.o: /usr/include/bits/types.h /usr/include/bits/wordsize.h
BHV_AvoidObstacles.o: /usr/include/bits/typesizes.h
BHV_AvoidObstacles.o: ../lib_geometry/AngleUtils.h
BHV_AvoidObstacles.o: ../lib_geometry/GeomUtils.h
BHV_AvoidObstacles.o: ../lib_ivpbuild/BuildUtils.h
BHV_CoWaypoint.o: /usr/include/math.h /usr/include/features.h
BHV_CoWaypoint.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
BHV_CoWaypoint.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
BHV_CoWaypoint.o: /usr/include/bits/mathcalls.h BHV_CoWaypoint.h
BHV_CoWaypoint.o: ../lib_behaviors/IvPBehavior.h ../lib_ivpcore/IvPFunction.h
BHV_CoWaypoint.o: ../lib_ivpcore/IvPBox.h ../lib_ivpcore/PDMap.h
BHV_CoWaypoint.o: ../lib_ivpcore/BoxSet.h ../lib_ivpcore/BoxSetNode.h
BHV_CoWaypoint.o: ../lib_ivpcore/IvPGrid.h ../lib_ivpcore/IvPDomain.h
BHV_CoWaypoint.o: ../lib_behaviors/InfoBuffer.h
BHV_CoWaypoint.o: ../lib_behaviors/VarDataPair.h
BHV_CoWaypoint.o: ../lib_logic/LogicCondition.h ../lib_logic/ParseNode.h
BHV_CoWaypoint.o: ../lib_mbutil/MBUtils.h /usr/include/time.h
BHV_CoWaypoint.o: /usr/include/bits/time.h /usr/include/bits/types.h
BHV_CoWaypoint.o: /usr/include/bits/wordsize.h /usr/include/bits/typesizes.h
BHV_CoWaypoint.o: ../lib_ivpbuild/BuildUtils.h
BHV_CutRangeFCPA.o: /usr/include/math.h /usr/include/features.h
BHV_CutRangeFCPA.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
BHV_CutRangeFCPA.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
BHV_CutRangeFCPA.o: /usr/include/bits/mathcalls.h AOF_CutRangeFCPA.h
BHV_CutRangeFCPA.o: ../lib_ivpbuild/AOF.h ../lib_ivpcore/IvPBox.h
BHV_CutRangeFCPA.o: ../lib_ivpcore/IvPDomain.h ../lib_geometry/CPAEngine.h
BHV_CutRangeFCPA.o: BHV_CutRangeFCPA.h ../lib_behaviors/IvPBehavior.h
BHV_CutRangeFCPA.o: ../lib_ivpcore/IvPFunction.h ../lib_ivpcore/PDMap.h
BHV_CutRangeFCPA.o: ../lib_ivpcore/BoxSet.h ../lib_ivpcore/BoxSetNode.h
BHV_CutRangeFCPA.o: ../lib_ivpcore/IvPGrid.h ../lib_behaviors/InfoBuffer.h
BHV_CutRangeFCPA.o: ../lib_behaviors/VarDataPair.h
BHV_CutRangeFCPA.o: ../lib_logic/LogicCondition.h ../lib_logic/ParseNode.h
BHV_CutRangeFCPA.o: ../lib_ivpbuild/OF_Reflector.h
BHV_CutRangeFCPA.o: ../lib_ivpbuild/BuildUtils.h ../lib_mbutil/MBUtils.h
BHV_CutRangeFCPA.o: /usr/include/time.h /usr/include/bits/time.h
BHV_CutRangeFCPA.o: /usr/include/bits/types.h /usr/include/bits/wordsize.h
BHV_CutRangeFCPA.o: /usr/include/bits/typesizes.h
BHV_Generic.o: /usr/include/math.h /usr/include/features.h
BHV_Generic.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
BHV_Generic.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
BHV_Generic.o: /usr/include/bits/mathcalls.h ../lib_geometry/GeomUtils.h
BHV_Generic.o: BHV_Generic.h ../lib_behaviors/IvPBehavior.h
BHV_Generic.o: ../lib_ivpcore/IvPFunction.h ../lib_ivpcore/IvPBox.h
BHV_Generic.o: ../lib_ivpcore/PDMap.h ../lib_ivpcore/BoxSet.h
BHV_Generic.o: ../lib_ivpcore/BoxSetNode.h ../lib_ivpcore/IvPGrid.h
BHV_Generic.o: ../lib_ivpcore/IvPDomain.h ../lib_behaviors/InfoBuffer.h
BHV_Generic.o: ../lib_behaviors/VarDataPair.h ../lib_logic/LogicCondition.h
BHV_Generic.o: ../lib_logic/ParseNode.h ../lib_bhvutil/AOF_WPT2D.h
BHV_Generic.o: ../lib_ivpbuild/AOF.h ../lib_ivpbuild/OF_Reflector.h
BHV_Generic.o: ../lib_mbutil/MBUtils.h /usr/include/time.h
BHV_Generic.o: /usr/include/bits/time.h /usr/include/bits/types.h
BHV_Generic.o: /usr/include/bits/wordsize.h /usr/include/bits/typesizes.h
BHV_Generic.o: ../lib_ivpbuild/BuildUtils.h
BHV_LoiterMigrate.o: /usr/include/math.h /usr/include/features.h
BHV_LoiterMigrate.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
BHV_LoiterMigrate.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
BHV_LoiterMigrate.o: /usr/include/bits/mathcalls.h
BHV_LoiterMigrate.o: ../lib_geometry/AngleUtils.h BHV_LoiterMigrate.h
BHV_LoiterMigrate.o: ../lib_behaviors/IvPBehavior.h
BHV_LoiterMigrate.o: ../lib_ivpcore/IvPFunction.h ../lib_ivpcore/IvPBox.h
BHV_LoiterMigrate.o: ../lib_ivpcore/PDMap.h ../lib_ivpcore/BoxSet.h
BHV_LoiterMigrate.o: ../lib_ivpcore/BoxSetNode.h ../lib_ivpcore/IvPGrid.h
BHV_LoiterMigrate.o: ../lib_ivpcore/IvPDomain.h ../lib_behaviors/InfoBuffer.h
BHV_LoiterMigrate.o: ../lib_behaviors/VarDataPair.h
BHV_LoiterMigrate.o: ../lib_logic/LogicCondition.h ../lib_logic/ParseNode.h
BHV_LoiterMigrate.o: ../lib_geometry/XYPolygon.h ../lib_geometry/XYSegList.h
BHV_LoiterMigrate.o: ../lib_bhvutil/LoiterEngine.h
BHV_LoiterMigrate.o: ../lib_bhvutil/WaypointEngine.h Migrator.h
BHV_LoiterMigrate.o: ../lib_mbutil/MBUtils.h /usr/include/time.h
BHV_LoiterMigrate.o: /usr/include/bits/time.h /usr/include/bits/types.h
BHV_LoiterMigrate.o: /usr/include/bits/wordsize.h
BHV_LoiterMigrate.o: /usr/include/bits/typesizes.h
BHV_LoiterMigrate.o: ../lib_ivpbuild/BuildUtils.h ../lib_ivpbuild/ZAIC_PEAK.h
BHV_LoiterMigrate.o: ../lib_ivpbuild/OF_Coupler.h
BHV_ObeySpeedLimit.o: /usr/include/assert.h /usr/include/features.h
BHV_ObeySpeedLimit.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
BHV_ObeySpeedLimit.o: /usr/include/math.h /usr/include/bits/huge_val.h
BHV_ObeySpeedLimit.o: /usr/include/bits/mathdef.h
BHV_ObeySpeedLimit.o: /usr/include/bits/mathcalls.h BHV_ObeySpeedLimit.h
BHV_ObeySpeedLimit.o: ../lib_behaviors/IvPBehavior.h
BHV_ObeySpeedLimit.o: ../lib_ivpcore/IvPFunction.h ../lib_ivpcore/IvPBox.h
BHV_ObeySpeedLimit.o: ../lib_ivpcore/PDMap.h ../lib_ivpcore/BoxSet.h
BHV_ObeySpeedLimit.o: ../lib_ivpcore/BoxSetNode.h ../lib_ivpcore/IvPGrid.h
BHV_ObeySpeedLimit.o: ../lib_ivpcore/IvPDomain.h
BHV_ObeySpeedLimit.o: ../lib_behaviors/InfoBuffer.h
BHV_ObeySpeedLimit.o: ../lib_behaviors/VarDataPair.h
BHV_ObeySpeedLimit.o: ../lib_logic/LogicCondition.h ../lib_logic/ParseNode.h
BHV_ObeySpeedLimit.o: ../lib_mbutil/MBUtils.h /usr/include/time.h
BHV_ObeySpeedLimit.o: /usr/include/bits/time.h /usr/include/bits/types.h
BHV_ObeySpeedLimit.o: /usr/include/bits/wordsize.h
BHV_ObeySpeedLimit.o: /usr/include/bits/typesizes.h
BHV_ObeySpeedLimit.o: ../lib_ivpbuild/BuildUtils.h
BHV_OpArea.o: /usr/include/math.h /usr/include/features.h
BHV_OpArea.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
BHV_OpArea.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
BHV_OpArea.o: /usr/include/bits/mathcalls.h BHV_OpArea.h
BHV_OpArea.o: ../lib_geometry/XYPolygon.h ../lib_geometry/XYSegList.h
BHV_OpArea.o: ../lib_behaviors/IvPBehavior.h ../lib_ivpcore/IvPFunction.h
BHV_OpArea.o: ../lib_ivpcore/IvPBox.h ../lib_ivpcore/PDMap.h
BHV_OpArea.o: ../lib_ivpcore/BoxSet.h ../lib_ivpcore/BoxSetNode.h
BHV_OpArea.o: ../lib_ivpcore/IvPGrid.h ../lib_ivpcore/IvPDomain.h
BHV_OpArea.o: ../lib_behaviors/InfoBuffer.h ../lib_behaviors/VarDataPair.h
BHV_OpArea.o: ../lib_logic/LogicCondition.h ../lib_logic/ParseNode.h
BHV_OpArea.o: AOF_OpArea.h ../lib_ivpbuild/AOF.h
BHV_OpArea.o: ../lib_ivpbuild/OF_Reflector.h ../lib_mbutil/MBUtils.h
BHV_OpArea.o: /usr/include/time.h /usr/include/bits/time.h
BHV_OpArea.o: /usr/include/bits/types.h /usr/include/bits/wordsize.h
BHV_OpArea.o: /usr/include/bits/typesizes.h ../lib_ivpbuild/BuildUtils.h
BHV_SearchGrid.o: BHV_SearchGrid.h ../lib_behaviors/IvPBehavior.h
BHV_SearchGrid.o: ../lib_ivpcore/IvPFunction.h ../lib_ivpcore/IvPBox.h
BHV_SearchGrid.o: ../lib_ivpcore/PDMap.h ../lib_ivpcore/BoxSet.h
BHV_SearchGrid.o: ../lib_ivpcore/BoxSetNode.h ../lib_ivpcore/IvPGrid.h
BHV_SearchGrid.o: ../lib_ivpcore/IvPDomain.h ../lib_behaviors/InfoBuffer.h
BHV_SearchGrid.o: ../lib_behaviors/VarDataPair.h
BHV_SearchGrid.o: ../lib_logic/LogicCondition.h ../lib_logic/ParseNode.h
BHV_SearchGrid.o: ../lib_geometry/XYGrid.h ../lib_geometry/XYSquare.h
BHV_SearchGrid.o: ../lib_geometry/XYPolygon.h ../lib_geometry/XYSegList.h
BHV_SearchGrid.o: Timutif.h AOF_SearchGrid.h ../lib_ivpbuild/AOF.h
BHV_SearchGrid.o: ../lib_mbutil/MBUtils.h /usr/include/time.h
BHV_SearchGrid.o: /usr/include/features.h /usr/include/sys/cdefs.h
BHV_SearchGrid.o: /usr/include/gnu/stubs.h /usr/include/bits/time.h
BHV_SearchGrid.o: /usr/include/bits/types.h /usr/include/bits/wordsize.h
BHV_SearchGrid.o: /usr/include/bits/typesizes.h
BHV_SearchGrid.o: ../lib_ivpbuild/OF_Reflector.h ../lib_ivpbuild/BuildUtils.h
BHV_SteadyHeading.o: /usr/include/math.h /usr/include/features.h
BHV_SteadyHeading.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
BHV_SteadyHeading.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
BHV_SteadyHeading.o: /usr/include/bits/mathcalls.h BHV_SteadyHeading.h
BHV_SteadyHeading.o: ../lib_behaviors/IvPBehavior.h
BHV_SteadyHeading.o: ../lib_ivpcore/IvPFunction.h ../lib_ivpcore/IvPBox.h
BHV_SteadyHeading.o: ../lib_ivpcore/PDMap.h ../lib_ivpcore/BoxSet.h
BHV_SteadyHeading.o: ../lib_ivpcore/BoxSetNode.h ../lib_ivpcore/IvPGrid.h
BHV_SteadyHeading.o: ../lib_ivpcore/IvPDomain.h ../lib_behaviors/InfoBuffer.h
BHV_SteadyHeading.o: ../lib_behaviors/VarDataPair.h
BHV_SteadyHeading.o: ../lib_logic/LogicCondition.h ../lib_logic/ParseNode.h
BHV_SteadyHeading.o: ../lib_ivpbuild/ZAIC_PEAK.h ../lib_ivpbuild/BuildUtils.h
BHV_SteadyHeading.o: ../lib_mbutil/MBUtils.h /usr/include/time.h
BHV_SteadyHeading.o: /usr/include/bits/time.h /usr/include/bits/types.h
BHV_SteadyHeading.o: /usr/include/bits/wordsize.h
BHV_SteadyHeading.o: /usr/include/bits/typesizes.h
BHV_SteadyHeading.o: ../lib_geometry/AngleUtils.h
BHV_TOL.o: ../lib_ivpbuild/IO_Utilities.h /usr/include/stdio.h
BHV_TOL.o: /usr/include/features.h /usr/include/sys/cdefs.h
BHV_TOL.o: /usr/include/gnu/stubs.h /usr/include/bits/types.h
BHV_TOL.o: /usr/include/bits/wordsize.h /usr/include/bits/typesizes.h
BHV_TOL.o: /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h
BHV_TOL.o: /usr/include/bits/wchar.h /usr/include/gconv.h
BHV_TOL.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
BHV_TOL.o: ../lib_ivpcore/IvPProblem.h ../lib_ivpcore/Problem.h
BHV_TOL.o: ../lib_ivpcore/IvPFunction.h ../lib_ivpcore/IvPBox.h
BHV_TOL.o: ../lib_ivpcore/PDMap.h ../lib_ivpcore/BoxSet.h
BHV_TOL.o: ../lib_ivpcore/BoxSetNode.h ../lib_ivpcore/IvPGrid.h
BHV_TOL.o: ../lib_ivpcore/IvPDomain.h ../lib_ivpcore/Compactor.h BHV_TOL.h
BHV_TOL.o: ../lib_behaviors/IvPBehavior.h ../lib_behaviors/InfoBuffer.h
BHV_TOL.o: ../lib_behaviors/VarDataPair.h ../lib_logic/LogicCondition.h
BHV_TOL.o: ../lib_logic/ParseNode.h AOF_TOL.h ../lib_ivpbuild/AOF.h
BHV_TOL.o: ../lib_ivpbuild/OF_Reflector.h ../lib_ivpbuild/BuildUtils.h
BHV_Waypoint2D.o: /usr/include/math.h /usr/include/features.h
BHV_Waypoint2D.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
BHV_Waypoint2D.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
BHV_Waypoint2D.o: /usr/include/bits/mathcalls.h BHV_Waypoint2D.h
BHV_Waypoint2D.o: ../lib_behaviors/IvPBehavior.h ../lib_ivpcore/IvPFunction.h
BHV_Waypoint2D.o: ../lib_ivpcore/IvPBox.h ../lib_ivpcore/PDMap.h
BHV_Waypoint2D.o: ../lib_ivpcore/BoxSet.h ../lib_ivpcore/BoxSetNode.h
BHV_Waypoint2D.o: ../lib_ivpcore/IvPGrid.h ../lib_ivpcore/IvPDomain.h
BHV_Waypoint2D.o: ../lib_behaviors/InfoBuffer.h
BHV_Waypoint2D.o: ../lib_behaviors/VarDataPair.h
BHV_Waypoint2D.o: ../lib_logic/LogicCondition.h ../lib_logic/ParseNode.h
BHV_Waypoint2D.o: ../lib_geometry/XYSegList.h AOF_Waypoint2D.h
BHV_Waypoint2D.o: ../lib_ivpbuild/AOF.h ../lib_geometry/AngleUtils.h
BHV_Waypoint2D.o: ../lib_ivpbuild/OF_Reflector.h ../lib_ivpbuild/BuildUtils.h
BHV_WaypointB.o: /usr/include/math.h /usr/include/features.h
BHV_WaypointB.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
BHV_WaypointB.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
BHV_WaypointB.o: /usr/include/bits/mathcalls.h BHV_WaypointB.h
BHV_WaypointB.o: ../lib_behaviors/IvPBehavior.h ../lib_ivpcore/IvPFunction.h
BHV_WaypointB.o: ../lib_ivpcore/IvPBox.h ../lib_ivpcore/PDMap.h
BHV_WaypointB.o: ../lib_ivpcore/BoxSet.h ../lib_ivpcore/BoxSetNode.h
BHV_WaypointB.o: ../lib_ivpcore/IvPGrid.h ../lib_ivpcore/IvPDomain.h
BHV_WaypointB.o: ../lib_behaviors/InfoBuffer.h ../lib_behaviors/VarDataPair.h
BHV_WaypointB.o: ../lib_logic/LogicCondition.h ../lib_logic/ParseNode.h
BHV_WaypointB.o: ../lib_geometry/XYSegList.h ../lib_ivpbuild/ZAIC_PEAK.h
BHV_WaypointB.o: ../lib_mbutil/MBUtils.h /usr/include/time.h
BHV_WaypointB.o: /usr/include/bits/time.h /usr/include/bits/types.h
BHV_WaypointB.o: /usr/include/bits/wordsize.h /usr/include/bits/typesizes.h
BHV_WaypointB.o: ../lib_geometry/AngleUtils.h ../lib_geometry/GeomUtils.h
BHV_WaypointB.o: ../lib_ivpbuild/BuildUtils.h
BHV_WaypointB.o: ../lib_ivpbuild/FunctionEncoder.h
BHV_WaypointB.o: ../lib_ivpbuild/OF_Coupler.h
BHV_WaypointOx.o: /usr/include/math.h /usr/include/features.h
BHV_WaypointOx.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
BHV_WaypointOx.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
BHV_WaypointOx.o: /usr/include/bits/mathcalls.h BHV_WaypointOx.h
BHV_WaypointOx.o: ../lib_geometry/XYSegList.h AOF_WaypointRateClosure.h
BHV_WaypointOx.o: ../lib_ivpbuild/AOF.h ../lib_ivpcore/IvPBox.h
BHV_WaypointOx.o: ../lib_ivpcore/IvPDomain.h ../lib_ivpbuild/OF_Reflector.h
BHV_WaypointOx.o: ../lib_mbutil/MBUtils.h /usr/include/time.h
BHV_WaypointOx.o: /usr/include/bits/time.h /usr/include/bits/types.h
BHV_WaypointOx.o: /usr/include/bits/wordsize.h /usr/include/bits/typesizes.h
BHV_WaypointOx.o: ../lib_geometry/AngleUtils.h ../lib_geometry/GeomUtils.h
BHV_WaypointOx.o: ../lib_ivpbuild/BuildUtils.h ../lib_ivpcore/PDMap.h
BHV_WaypointOx.o: ../lib_ivpcore/BoxSet.h ../lib_ivpcore/BoxSetNode.h
BHV_WaypointOx.o: ../lib_ivpcore/IvPGrid.h ../lib_ivpbuild/FunctionEncoder.h
BHV_WaypointOx.o: ../lib_ivpcore/IvPFunction.h ../lib_ivpbuild/ZAIC_PEAK.h
BHV_WaypointOx.o: ../lib_ivpbuild/OF_Coupler.h
BHV_WaypointRC.o: /usr/include/math.h /usr/include/features.h
BHV_WaypointRC.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
BHV_WaypointRC.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
BHV_WaypointRC.o: /usr/include/bits/mathcalls.h BHV_WaypointRC.h
BHV_WaypointRC.o: ../lib_behaviors/IvPBehavior.h ../lib_ivpcore/IvPFunction.h
BHV_WaypointRC.o: ../lib_ivpcore/IvPBox.h ../lib_ivpcore/PDMap.h
BHV_WaypointRC.o: ../lib_ivpcore/BoxSet.h ../lib_ivpcore/BoxSetNode.h
BHV_WaypointRC.o: ../lib_ivpcore/IvPGrid.h ../lib_ivpcore/IvPDomain.h
BHV_WaypointRC.o: ../lib_behaviors/InfoBuffer.h
BHV_WaypointRC.o: ../lib_behaviors/VarDataPair.h
BHV_WaypointRC.o: ../lib_logic/LogicCondition.h ../lib_logic/ParseNode.h
BHV_WaypointRC.o: ../lib_geometry/XYSegList.h AOF_WaypointRateClosure.h
BHV_WaypointRC.o: ../lib_ivpbuild/AOF.h ../lib_ivpbuild/OF_Reflector.h
BHV_WaypointRC.o: ../lib_mbutil/MBUtils.h /usr/include/time.h
BHV_WaypointRC.o: /usr/include/bits/time.h /usr/include/bits/types.h
BHV_WaypointRC.o: /usr/include/bits/wordsize.h /usr/include/bits/typesizes.h
BHV_WaypointRC.o: ../lib_geometry/AngleUtils.h ../lib_geometry/GeomUtils.h
BHV_WaypointRC.o: ../lib_ivpbuild/BuildUtils.h
BHV_WaypointRC.o: ../lib_ivpbuild/FunctionEncoder.h
BHV_WaypointRC.o: ../lib_ivpbuild/ZAIC_PEAK.h ../lib_ivpbuild/OF_Coupler.h
BHV_WaypointSimple.o: ../lib_mbutil/MBTimer.h /usr/include/sys/times.h
BHV_WaypointSimple.o: /usr/include/features.h /usr/include/sys/cdefs.h
BHV_WaypointSimple.o: /usr/include/gnu/stubs.h /usr/include/time.h
BHV_WaypointSimple.o: /usr/include/bits/time.h /usr/include/bits/types.h
BHV_WaypointSimple.o: /usr/include/bits/wordsize.h
BHV_WaypointSimple.o: /usr/include/bits/typesizes.h /usr/include/math.h
BHV_WaypointSimple.o: /usr/include/bits/huge_val.h
BHV_WaypointSimple.o: /usr/include/bits/mathdef.h
BHV_WaypointSimple.o: /usr/include/bits/mathcalls.h BHV_WaypointSimple.h
BHV_WaypointSimple.o: ../lib_behaviors/IvPBehavior.h
BHV_WaypointSimple.o: ../lib_ivpcore/IvPFunction.h ../lib_ivpcore/IvPBox.h
BHV_WaypointSimple.o: ../lib_ivpcore/PDMap.h ../lib_ivpcore/BoxSet.h
BHV_WaypointSimple.o: ../lib_ivpcore/BoxSetNode.h ../lib_ivpcore/IvPGrid.h
BHV_WaypointSimple.o: ../lib_ivpcore/IvPDomain.h
BHV_WaypointSimple.o: ../lib_behaviors/InfoBuffer.h
BHV_WaypointSimple.o: ../lib_behaviors/VarDataPair.h
BHV_WaypointSimple.o: ../lib_logic/LogicCondition.h ../lib_logic/ParseNode.h
BHV_WaypointSimple.o: ../lib_geometry/XYSegList.h AOF_WaypointRateClosure.h
BHV_WaypointSimple.o: ../lib_ivpbuild/AOF.h ../lib_ivpbuild/OF_Reflector.h
BHV_WaypointSimple.o: ../lib_mbutil/MBUtils.h ../lib_geometry/AngleUtils.h
BHV_WaypointSimple.o: ../lib_ivpbuild/BuildUtils.h
BHV_WaypointSimple.o: ../lib_ivpbuild/ZAIC_PEAK.h
BHV_WaypointSimple.o: ../lib_ivpbuild/OF_Coupler.h
BHV_WaypointTOL.o: /usr/include/math.h /usr/include/features.h
BHV_WaypointTOL.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
BHV_WaypointTOL.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
BHV_WaypointTOL.o: /usr/include/bits/mathcalls.h BHV_WaypointTOL.h
BHV_WaypointTOL.o: ../lib_behaviors/IvPBehavior.h
BHV_WaypointTOL.o: ../lib_ivpcore/IvPFunction.h ../lib_ivpcore/IvPBox.h
BHV_WaypointTOL.o: ../lib_ivpcore/PDMap.h ../lib_ivpcore/BoxSet.h
BHV_WaypointTOL.o: ../lib_ivpcore/BoxSetNode.h ../lib_ivpcore/IvPGrid.h
BHV_WaypointTOL.o: ../lib_ivpcore/IvPDomain.h ../lib_behaviors/InfoBuffer.h
BHV_WaypointTOL.o: ../lib_behaviors/VarDataPair.h
BHV_WaypointTOL.o: ../lib_logic/LogicCondition.h ../lib_logic/ParseNode.h
BHV_WaypointTOL.o: ../lib_geometry/XYSegList.h ../lib_bhvutil/AOF_WPT2D.h
BHV_WaypointTOL.o: ../lib_ivpbuild/AOF.h ../lib_ivpbuild/OF_Reflector.h
BHV_WaypointTOL.o: ../lib_mbutil/MBUtils.h /usr/include/time.h
BHV_WaypointTOL.o: /usr/include/bits/time.h /usr/include/bits/types.h
BHV_WaypointTOL.o: /usr/include/bits/wordsize.h /usr/include/bits/typesizes.h
BHV_WaypointTOL.o: ../lib_geometry/AngleUtils.h ../lib_geometry/GeomUtils.h
BHV_WaypointTOL.o: ../lib_ivpbuild/BuildUtils.h
BHV_WaypointTOL.o: ../lib_ivpbuild/FunctionEncoder.h
Migrator.o: /usr/include/math.h /usr/include/features.h
Migrator.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
Migrator.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
Migrator.o: /usr/include/bits/mathcalls.h Migrator.h
Migrator.o: ../lib_geometry/XYSegList.h
Timutif.o: Timutif.h ../lib_mbutil/MBUtils.h /usr/include/time.h
Timutif.o: /usr/include/features.h /usr/include/sys/cdefs.h
Timutif.o: /usr/include/gnu/stubs.h /usr/include/bits/time.h
Timutif.o: /usr/include/bits/types.h /usr/include/bits/wordsize.h
Timutif.o: /usr/include/bits/typesizes.h
