# Generated by CMake 2.6-patch 2

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" GREATER 2.4)
  # Information for CMake 2.6 and above.
  SET("fltk_LIB_DEPENDS" "general;/usr/lib/libSM.so;general;/usr/lib/libICE.so;general;/usr/lib/libX11.so;general;/usr/lib/libXext.so;general;-lm;general;-lpthread;general;/usr/lib/libSM.so;general;/usr/lib/libICE.so;general;/usr/lib/libX11.so;general;/usr/lib/libXext.so;")
  SET("fltk_forms_LIB_DEPENDS" "general;fltk;")
  SET("fltk_gl_LIB_DEPENDS" "general;fltk;general;/usr/lib/libGL.so;general;/usr/lib/libSM.so;general;/usr/lib/libICE.so;general;/usr/lib/libX11.so;general;/usr/lib/libXext.so;")
  SET("fltk_images_LIB_DEPENDS" "general;fltk;general;fltk_png;general;fltk_jpeg;general;fltk_zlib;")
  SET("fltk_png_LIB_DEPENDS" "general;fltk_zlib;general;-lm;")
  SET("ivpbuild_LIB_DEPENDS" "general;ivpcore;")
  SET("marineview_LIB_DEPENDS" "general;fltk;general;fltk_gl;")
  SET("navplot_LIB_DEPENDS" "general;ivpbuild;")
ELSE("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" GREATER 2.4)
  # Information for CMake 2.4 and lower.
  SET("fltk_LIB_DEPENDS" "/usr/lib/libSM.so;/usr/lib/libICE.so;/usr/lib/libX11.so;/usr/lib/libXext.so;-lm;-lpthread;/usr/lib/libSM.so;/usr/lib/libICE.so;/usr/lib/libX11.so;/usr/lib/libXext.so;")
  SET("fltk_forms_LIB_DEPENDS" "fltk;")
  SET("fltk_gl_LIB_DEPENDS" "fltk;/usr/lib/libGL.so;/usr/lib/libSM.so;/usr/lib/libICE.so;/usr/lib/libX11.so;/usr/lib/libXext.so;")
  SET("fltk_images_LIB_DEPENDS" "fltk;fltk_png;fltk_jpeg;fltk_zlib;")
  SET("fltk_png_LIB_DEPENDS" "fltk_zlib;-lm;")
  SET("ivpbuild_LIB_DEPENDS" "ivpcore;")
  SET("marineview_LIB_DEPENDS" "fltk;fltk_gl;")
  SET("navplot_LIB_DEPENDS" "ivpbuild;")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" GREATER 2.4)
