# Makefile definitions particular to the fltkvw library

LTARGET  = libfltkvw.a
LIFLAGS  = $(patsubst %,-I%,$(LIB_FLTK))
LCFLAGS  = 

# Make configuration parameters
include ../make_config.mk
# Generic makefile structure for all library modules
include ../make_lib.mk
# DO NOT DELETE
