PROG_NAME   = p1BTracker
SOURCE_LIST = 1BTrack.cpp \
              p1BTrackMain.cpp \
	      1BTracker.cpp

DEP_LIST = MOOS_LIB MOOS_GEN MOOS_OPT

all: $(PROG_NAME)

include ../../../../configuration.mk
include ../../../../build_program.mk
