# Makefile definitions particular to the artifactfield library

LTARGET  = libartifacts.a
LIFLAGS  = 
LCFLAGS  = 

# Make configuration parameters
include ../../make_config.mk
# Generic makefile structure for all library modules
include ../../make_lib.mk
# DO NOT DELETE
