# Makefile definitions particular to behaviors-marine library

LTARGET  = libbehaviors-marine.a
LIFLAGS  = 
LCFLAGS  = 

# Make configuration parameters
include ../make_config.mk
# Generic makefile structure for all library modules
include ../make_lib.mk
# DO NOT DELETE
