# Makefile definitions particular to the helmivp library

LTARGET  = libhelmivp.a
LIFLAGS  = 
LCFLAGS  = -DDATA_DIR="\"$(DATA_DIR)"\"

# Make configuration parameters
include ../make_config.mk
# Generic makefile structure for all library modules
include ../make_lib.mk
# DO NOT DELETE
