# IF("${PACKAGE_VERSION}" STREQUAL "")
#    MESSAGE(FATAL_ERROR "PACKAGE_VERSION wasn't specified")
# ENDIF("${PACKAGE_VERSION}" STREQUAL "")

IF("${INPUT_FILE}" STREQUAL "")
   MESSAGE(FATAL_ERROR "INPUT_FILE wasn't specified")
ENDIF("${INPUT_FILE}" STREQUAL "")

IF("${OUTPUT_FILE}" STREQUAL "")
   MESSAGE(FATAL_ERROR "OUTPUT_FILE wasn't specified")
ENDIF("${OUTPUT_FILE}" STREQUAL "")


GET_FILENAME_COMPONENT(INPUT_FILE ${INPUT_FILE} ABSOLUTE)
GET_FILENAME_COMPONENT(OUTPUT_FILE ${OUTPUT_FILE} ABSOLUTE)

CONFIGURE_FILE("${INPUT_FILE}" "${OUTPUT_FILE}" @ONLY)
