# Makefile definitions particular to the anrp_util library

LTARGET  = libanrp_util.a
LIFLAGS  = 
LCFLAGS  = 

# Make configuration parameters
include ../../make_config.mk
# Generic makefile structure for all library modules
include ../../make_lib.mk
# DO NOT DELETE
