# Makefile definitions particular to MOOSLIB library

LTARGET  = libMOOSUtilityLib.a
LIFLAGS  = -I../MOOSGenLib -I../MOOSLIB
LCFLAGS  = -DUNIX

# Make configuration parameters
include ../make_config.mk
# Generic makefile structure for all library modules
include ../make_lib.mk
# DO NOT DELETE
