#!/bin/bash 


# Example_config.sh pFoobar
#
# 1. check whether pFoobar exists
#    exit if it does NOT exist
# 2. check whether pFoobar.moos already exists
#    exit if it DOES exist.
# 3. output a header indicating this is auto generated
# 4. Run pMarineViewer -e 

if [ $# -ne 1 ]
then
  echo "Usage: example_config.sh <command_name>"
  exit 0
fi


CMD=$1
FILE=$1.moos

echo Command $CMD
echo FILE    $FILE

if [ ! -e $FILE ] ; then
    echo File $FILE does not exist. Exiting
    exit 0;
fi
echo File $FILE does exist.

if which $CMD >& /dev/null; then
    echo The Command $CMD is found
else
    echo The Command $CMD is not found
    exit 0;
fi

echo The following example configuration was auto-generated by running: > $FILE
echo \$ $CMD -e > $FILE
echo > $FILE
exec $1 -e > $FILE
echo File $FILE successfully updated.



exit 0


