#!/bin/bash

if [ -z "$1" ] ; then
    echo "GenMOOSApp: usage: $0 [app-name] [prefix]"
    exit 0
fi

if [ -z "$2" ] ; then
    echo "GenMOOSApp: usage: $0 [app-name] [prefix]"
    exit 0
fi

#if [ -z "$3" ] ; then
#    $3="YOUR-NAME-HERE"
#fi

mkdir $2$1
cd $2$1

cat >> CMakeLists.txt <<EOF
#--------------------------------------------------------
# The CMakeLists.txt for:                       $2$1
# Author(s):                              $3
#--------------------------------------------------------

FILE(GLOB SRC *.cpp)

ADD_EXECUTABLE($2$1 \${SRC})

TARGET_LINK_LIBRARIES($2$1
   MOOS
   MOOSGen
   mbutil
   m
   pthread)

EOF


cat >> ${1}.h <<EOF
/************************************************************/
/*    NAME: $3                                              */
/*    ORGN: MIT                                             */
/*    FILE: ${1}.h                                          */
/*    DATE:                                                 */
/************************************************************/

#ifndef ${1}_HEADER
#define ${1}_HEADER

#include "MOOSLib.h"

class ${1} : public CMOOSApp
{
public:
	${1}();
	virtual ~${1}();

	bool OnNewMail(MOOSMSG_LIST &NewMail);
	bool Iterate();
	bool OnConnectToServer();
	bool OnStartUp();

protected:
	// insert local vars here
};

#endif 
EOF

cat >> main.cpp <<EOF
/************************************************************/
/*    NAME: $3                                              */
/*    ORGN: MIT                                             */
/*    FILE: main.cpp                                        */
/*    DATE:                                                 */
/************************************************************/

#include <string>
#include "MOOSLib.h"
#include "MOOSGenLib.h"
#include "MBUtils.h"
#include "${1}_ExampleConfig.h"
#include "${1}.h"

using namespace std;

int main(int argc, char *argv[])
{
  string mission_file = "";
  string run_command  = argv[0];
  bool   help_requested = false;
  bool   vers_requested = false;
  bool   exam_requested = false;

  int    i;
  for(i=1; i<argc; i++) {
    string argi = argv[i];
    if((argi=="-v") || (argi=="--version") || (argi=="-version"))
      vers_requested = true;
    else if((argi=="-e") || (argi=="--example") || (argi=="-example"))
      exam_requested = true;
    else if((argi == "--help")||(argi=="-h"))
      help_requested = true;
    else if(strEnds(argi, ".moos") || strEnds(argi, ".moos++"))
      mission_file = argv[i];
    else if(strBegins(argi, "--alias="))
      run_command = argi.substr(8);
  }
  
  if(vers_requested) {
    cout << "${2}${1} Version 0.1" << endl;
    return(0);
  }

  if(exam_requested) {
    showExampleConfig();
    return(0);
  }

  if((mission_file == "") || help_requested) {
    cout << "Usage: ${2}${1} file.moos [OPTIONS]                 " << endl;
    cout << "                                                    " << endl;
    cout << "Options:                                            " << endl;
    cout << "  --alias=<ProcessName>                             " << endl;
    cout << "      Launch ${2}${1} with the given process  " << endl;
    cout << "      name rather than ${2}${1}.               " << endl;
    cout << "  --example, -e                                     " << endl;
    cout << "      Display example MOOS configuration block.     " << endl;
    cout << "  --help, -h                                        " << endl;
    cout << "      Display this help message.                    " << endl;
    cout << "  --version,-v                                      " << endl;
    cout << "      Display the release version of ${2}${1}. " << endl;
    return(0);
  }

  cout << "${2}${1} running as: " << run_command << endl;

  ${1} ${1};

  ${1}.Run(run_command.c_str(), mission_file.c_str());
  
  return(0);
}

EOF

cat >> $2${1}.moos <<EOF
// MOOS file

ServerHost = localhost
ServerPort = 9000

ProcessConfig = ${2}${1}
{
   AppTick   = 4
   CommsTick = 4
}

EOF

cat >> ${1}.cpp <<EOF
/************************************************************/
/*    NAME: $3                                              */
/*    ORGN: MIT                                             */
/*    FILE: ${1}.cpp                                        */
/*    DATE:                                                 */
/************************************************************/

#include <iterator>
#include "${1}.h"
//---------------------------------------------------------
// Constructor

${1}::${1}()
{
}

//---------------------------------------------------------
// Destructor

${1}::~${1}()
{
}

//---------------------------------------------------------
// Procedure: OnNewMail

bool ${1}::OnNewMail(MOOSMSG_LIST &NewMail)
{
   MOOSMSG_LIST::iterator p;
   
   for(p=NewMail.begin(); p!=NewMail.end(); p++) {
      CMOOSMsg &msg = *p;
   }
	
   return(true);
}

//---------------------------------------------------------
// Procedure: OnConnectToServer

bool ${1}::OnConnectToServer()
{
   // register for variables here
   // possibly look at the mission file?
   // m_MissionReader.GetConfigurationParam("Name", <string>);
   // m_Comms.Register("VARNAME", is_float(int));
	
   return(true);
}

//---------------------------------------------------------
// Procedure: Iterate()

bool ${1}::Iterate()
{
   // happens AppTick times per second
	
   return(true);
}

//---------------------------------------------------------
// Procedure: OnStartUp()

bool ${1}::OnStartUp()
{
   // happens before connection is open
	
   return(true);
}

EOF


cat >> ${1}_ExampleConfig.h <<EOF
/****************************************************************/
/*   NAME: ${3}                                             */
/*   ORGN: MIT Cambridge MA                                     */
/*   FILE: ${1}_ExampleConfig.h                            */
/*   DATE: Dec 29th 1963                                        */
/****************************************************************/

#ifndef ${1}_EXAMPLE_CONFIG_HEADER
#define ${1}_EXAMPLE_CONFIG_HEADER

void showExampleConfig();

#endif

EOF


cat >> ${1}_ExampleConfig.cpp <<EOF
/****************************************************************/
/*   NAME: ${3}                                             */
/*   ORGN: MIT Cambridge MA                                     */
/*   FILE: ${1}_ExampleConfig.cpp                               */
/*   DATE: Dec 29th 1963                                        */
/****************************************************************/

#include <iostream>
#include "${1}_ExampleConfig.h"
#include "ColorParse.h"

using namespace std;

//----------------------------------------------------------------
// Procedure: showExampleConfig                                  

void showExampleConfig()
{
  cout << "                                                   " << endl;
  cout << "===================================================" << endl;
  cout << "${2}${1} Example MOOS Configuration                " << endl;
  cout << "===================================================" << endl;
  cout << "                                                   " << endl;
  cout << "ProcessConfig = ${2}${1}                           " << endl;
  cout << "{                                                  " << endl;
  cout << "  AppTick   = 4                                    " << endl;
  cout << "  CommsTick = 4                                    " << endl;
  cout << "                                                   " << endl;
  cout << "  Port = /dev/ttyUSB0                              " << endl;
  cout << "  Timeout = 6                                      " << endl;
  cout << "                                                   " << endl;
  cout << "  // If 1 then heading computed from magnetometers " << endl;
  cout << "  ComputeHeading = 0                               " << endl;
  cout << "                                                   " << endl;
}
EOF


echo "$2${1} generated"
