# Version Configuration file for MOOS library.
set(PACKAGE_VERSION "10.0.1")

if("${PACKAGE_FIND_VERSION_MAJOR}" EQUAL 10 )
   set(PACKAGE_VERSION_COMPATIBLE 1) 
   if("${PACKAGE_FIND_VERSION_MINOR}" EQUAL 0 )
     set(PACKAGE_VERSION_EXACT 1)   
   endif("${PACKAGE_FIND_VERSION_MINOR}" EQUAL 0 )
endif("${PACKAGE_FIND_VERSION_MAJOR}" EQUAL 10 )
